name: Lokalise sync

# on:
#   push:
#     branches:
#       - develop

on:
  pull_request:
    types: [closed]

jobs:
  lokalise-sync:
    # if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_REF#refs/heads/}
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Check for changes in locales/en.json
      #   id: check_changes
      #   run: |
      #     if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^locales\/.*en\.json$'; then
      #       echo "Changes detected in locales/en.json"
      #       echo "::set-output name=changes::true"
      #     else
      #       echo "No changes detected in locales/en.json"
      #       echo "::set-output name=changes::false"
      #     fi

      # - name: Run Script if changes detected
      #   if: steps.check_changes.outputs.changes == 'true'
      #   run: |
      #     # Add your script commands here
      #     echo "Running script because changes were made to locales/en.json"

# on:
#   pull_request:
#     branches:
#       - develop
#     paths:
#       - 'locales/**en.json'
#   workflow_dispatch:
#   workflow_run:
#     workflows: ["Push"]
#     types: completed

# jobs:
#   deploy-argocd-preview-image:
#     runs-on: arc-runner-set



# 1. Check if branch is develop or master or not the branch



# ### Upload
# npm run locales:upload // Uploads modified EN files with current branch prefix
# npm run locales:upload --master // Upload modified EN files with master prefix (Hotfix case)
# npm run locales:upload --all // Uploads all EN files with master prefix

# ### Download
# npm run locales:download // Downloads all files from current branch prefix
# npm run locales:download --master // Download all files from master prefix (Hotfix case)
