name: Push and Pull
on:
  pull_request:
    branches:
      - main
    paths:
      - "locales/**en.json"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lokalise CLI
        run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
      - name: Push
        env:
          VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
          VAR_LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
          ENV_LOKALISE_SOURCE_LANG_ISO: en
        run: |
          while read file 
          do 
            if [ -f $file ]
            then
              ./bin/lokalise2 --token ${{ env.VAR_LOKALISE_API_TOKEN }} --project-id ${{ env.VAR_LOKALISE_PROJECT_ID }} file upload --file="${file}" --lang-iso ${{ env.ENV_LOKALISE_SOURCE_LANG_ISO }} --replace-modified --include-path --use-automations=true --cleanup-mode --poll-timeout 120s
            fi
          done < <(
          if [ -z ${{ github.event.after }} ]
          then
            git ls-files -- '**${{ env.ENV_LOKALISE_SOURCE_LANG_ISO }}.json'
          else
            git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- '**${{ env.ENV_LOKALISE_SOURCE_LANG_ISO }}.json'
          fi | awk NF)
      - name: Pull
        env:
          VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
          VAR_LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
        run: |
          ./bin/lokalise2 --token ${{ env.VAR_LOKALISE_API_TOKEN }} --project-id ${{ env.VAR_LOKALISE_PROJECT_ID }} file download --format json --original-filenames=true --directory-prefix=/
      - name: Create Branch and Push
        run: |
          NEW_BRANCH="translations-update-${GITHUB_RUN_ID}"
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH
          echo "NEW_BRANCH: $NEW_BRANCH"
      - name: Create PR with translations
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add locales/\*.json

          if [[ -z $(git status --untracked-files=no --porcelain) ]]
          then
            echo "No changes"
          else
            git commit -m "Translations update"

            NEW_BRANCH="translations-update-${GITHUB_RUN_ID}"

            echo "NEW_BRANCH: $NEW_BRANCH"

            gh pr create --base "${{ github.head_ref }}" --head "$NEW_BRANCH" --title "Translations Update" --body "This pull request updates translations."
