name: Push
on:
  pull_request:
    branches:
      - main
    paths:
      - "locales/**en.json"
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.get_branch.outputs.branch }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          path: .
      - name: Get Branch Name
        id: get_branch
        run: echo "::set-output name=branch::${{ github.event.pull_request.head.ref }}"
      - name: Lokalise CLI
        run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
      - name: Push
        env:
          GITHUB_PREVIOUS_COMMIT: ${{ github.event.after }}
          GITHUB_CURRENT_COMMIT: ${{ github.event.before }}
          VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
          VAR_LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
          ENV_LOKALISE_SOURCE_LANG_ISO: en
        run: |
          while read file 
          do 
            if [ -f $file ]
            then
              ./bin/lokalise2 --token ${{ env.VAR_LOKALISE_API_TOKEN }} --project-id ${{ env.VAR_LOKALISE_PROJECT_ID }} file upload --file="${file}" --lang-iso ${{ env.ENV_LOKALISE_SOURCE_LANG_ISO }} --replace-modified --include-path --use-automations=true --cleanup-mode --poll-timeout 120s
            fi
          done < <(
          if [ -z ${{ env.GITHUB_CURRENT_COMMIT }} ]
          then
            git ls-files -- '**${{ env.ENV_LOKALISE_SOURCE_LANG_ISO }}.json'
          else
            git diff --name-only ${{ env.GITHUB_PREVIOUS_COMMIT }} ${{ env.GITHUB_CURRENT_COMMIT }} -- '**${{ env.ENV_LOKALISE_SOURCE_LANG_ISO }}.json'
          fi | awk NF)
