name: Create Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create new branch and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the current branch name
          CURRENT_BRANCH=$(echo "${{ github.ref }}" | cut -d'/' -f3-)
          # Create a new branch based on the current branch
          NEW_BRANCH="new-branch-${{ github.run_number }}"
          git checkout -b $NEW_BRANCH "refs/heads/$CURRENT_BRANCH"
          # Make some changes to the code
          echo "New changes" >> README.md
          git add README.md
          git commit -m "New changes"
          # Push the changes to the new branch
          git push origin $NEW_BRANCH
          # Create a new pull request
          gh pr create --base $CURRENT_BRANCH --head $NEW_BRANCH --title "New Pull Request" --body "This is a new pull request based on the current pull request."
