name: Push and Pull
on:
  pull_request:
    branches:
      - main
    paths:
      - "locales/**en.json"
  workflow_dispatch:
  workflow_run:
    workflows: ["Push"]
    types: completed

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          path: .
      - name: Lokalise CLI (Push)
        run: |
          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
      - name: Push to Lokalise
        env:
          GITHUB_PREVIOUS_COMMIT: ${{ github.event.after }}
          GITHUB_CURRENT_COMMIT: ${{ github.event.before }}
          VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
          VAR_LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
          ENV_LOKALISE_SOURCE_LANG_ISO: en
        run: |
          while read file 
          do 
            if [ -f $file ]
            then
              ./bin/lokalise2 --token ${{ env.VAR_LOKALISE_API_TOKEN }} --project-id ${{ env.VAR_LOKALISE_PROJECT_ID }} file upload --file="${file}" --lang-iso ${{ env.ENV_LOKALISE_SOURCE_LANG_ISO }} --replace-modified --include-path --use-automations=true --cleanup-mode --poll-timeout 120s
            fi
          done < <(
            if [ -z ${{ env.GITHUB_CURRENT_COMMIT }} ]
            then
              git ls-files -- '**${{ env.ENV_LOKALISE_SOURCE_LANG_ISO }}.json'
            else
              git diff --name-only ${{ env.GITHUB_PREVIOUS_COMMIT }} ${{ env.GITHUB_CURRENT_COMMIT }} -- '**${{ env.ENV_LOKALISE_SOURCE_LANG_ISO }}.json'
            fi | awk NF)

  pull:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          path: .
      - name: Lokalise CLI (Pull)
        run: |
          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
      - name: Pull from Lokalise
        env:
          VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
          VAR_LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
        run: |
          ./bin/lokalise2 --token ${{ env.VAR_LOKALISE_API_TOKEN }} --project-id ${{ env.VAR_LOKALISE_PROJECT_ID }} file download --format json --original-filenames=true --directory-prefix=/
      - name: Create Branch and Push
        run: |
          NEW_BRANCH="translations-update-${GITHUB_RUN_ID}"
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH
      - name: Create PR with translations
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add locales/\*.json

          if [[ -z $(git status --untracked-files=no --porcelain) ]]
          then
            echo "No changes"
          else
            git commit -m "Translations update"

            NEW_BRANCH="translations-update-${GITHUB_RUN_ID}"

            gh pr create --base ${{ github.ref }} --head "$NEW_BRANCH" --title "Translations Update" --body "This pull request updates translations."
          fi
