name: Push and Pull Translations
on:
  pull_request:
    types: [opened]
    paths:
      - "locales/**en.json"
jobs:
  push-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Lokalise CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh -s -- -b $HOME/bin
          if [ -f $HOME/bin/lokalise2 ]
          then
            echo "Lokalise CLI installed successfully"
          else
            echo "Lokalise CLI installation failed"
            exit 1
          fi
      - name: Push translations to Lokalise
        env:
          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
          LOKALISE_SOURCE_LANG_ISO: en
        run: |
          while read file 
          do 
            if [ -f $file ]
            then
              output=$($HOME/bin/lokalise2 --token $LOKALISE_API_TOKEN --project-id $LOKALISE_PROJECT_ID file upload --file="${file}" --lang-iso $LOKALISE_SOURCE_LANG_ISO --replace-modified --include-path --use-automations=true --cleanup-mode --poll-timeout 120s)
              echo "Lokalise upload command output: $output"
            fi
          done < <(
          if [ -z ${{ github.event.after }} ]
          then
            output=$(git ls-files -- 'locales/**${LOKALISE_SOURCE_LANG_ISO}.json')
            echo "List of files to be uploaded: $output"
          else
            git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- 'locales/**${LOKALISE_SOURCE_LANG_ISO}.json'
          fi | awk NF)

  pull-translations:
    runs-on: ubuntu-latest
    needs: push-translations
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Lokalise CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh -s -- -b $HOME/bin
          if [ -f $HOME/bin/lokalise2 ]
          then
            echo "Lokalise CLI installed successfully"
          else
            echo "Lokalise CLI installation failed"
            exit 1
          fi
      - name: Pull translations from Lokalise
        env:
          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
        run: |
          $HOME/bin/lokalise2 --token $LOKALISE_API_TOKEN --project-id $LOKALISE_PROJECT_ID file download --format json --original-filenames=true --directory-prefix=/
          NEW_BRANCH="translations-update-${GITHUB_RUN_ID}"
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add locales/\*.json
          if [[ -z $(git status --untracked-files=no --porcelain) ]]
          then
            echo "No changes"
          else
            git commit -m "Translations update"
            gh pr create --base ${{ github.base_ref }} --head "$NEW_BRANCH" --title "Translations Update" --body "This pull request updates translations."
