name: Open Secondary Pull Request
on:
  pull_request:
    types:
      - opened
jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create New Branch
        run: |
          # Generate a unique branch name for the new PR
          NEW_BRANCH="secondary-pr-$(date +%s)"
          
          # Create a new branch based on the source branch of the pull request
          git checkout -b $NEW_BRANCH ${{ github.event.pull_request.head.ref }}
          
          # Push the new branch to the repository
          git push origin $NEW_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create New Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Create secondary pull request"
          title: "Secondary Pull Request"
          base: ${{ github.event.pull_request.head.ref }}
          branch: $NEW_BRANCH
