name: Translation Workflow
on:
  pull_request:
    branches:
      - main
    paths:
      - "locales/**en.json"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lokalise CLI
        run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
      - name: Push
        env:
          VAR_LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
          VAR_LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
          ENV_LOKALISE_SOURCE_LANG_ISO: en
        run: |
          while read file
          do
             if [ -f $file ]
             then
               ./bin/lokalise2 --token $VAR_LOKALISE_API_TOKEN --project-id $VAR_LOKALISE_PROJECT_ID file upload --file="${file}" --lang-iso $ENV_LOKALISE_SOURCE_LANG_ISO --replace-modified --include-path --use-automations=true --cleanup-mode --poll-timeout 120s
             fi
          done < <(
          if [ -z ${{ github.event.before }} ]
          then
           git ls-files -- 'locales/**${ENV_LOKALISE_SOURCE_LANG_ISO}.json'
          else
           git diff --name-only ${{ github.event.after }} ${{ github.event.before }} -- 'locales/**${ENV_LOKALISE_SOURCE_LANG_ISO}.json'
          fi | awk NF)
